rest-client:
  services:

    stripe:
      url: https://api.stripe.com/v1
      connection-time-out: 3000
      read-time-out: 5000

    github:
      url: https://api.github.com
      connection-time-out: 4000
      read-time-out: 7000

    viacep:
      url: https://viacep.com.br/ws
      connection-time-out: 2000
      read-time-out: 3000

